image: elixir:1.9.0
services:
  - rabbitmq:3.7

variables:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  AMQP_URL: "amqp://guest:guest@rabbitmq:5672"
  MIX_ENV: "test"

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

stages:
  - test

test:
  stage: test
  script:
    - mix test
